/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ecowiseApp;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Erin Lee
 */
public class EcowiseGUI extends javax.swing.JFrame {
    public ArrayList <customer> customers;
    public ArrayList <shopCart> cart;

    /**
     * Creates new form shopFrame
     */
    public EcowiseGUI() {
        initComponents();
    }
    
    public void setColor(JPanel panel){
        panel.setBackground(new Color(212,232,193));
    }
    public void resetColor(JPanel panel){
        panel.setBackground(new Color(141,184,124));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarMenu = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        homeLbl = new javax.swing.JLabel();
        homeTxt = new javax.swing.JLabel();
        shopPanel = new javax.swing.JPanel();
        shopLbl = new javax.swing.JLabel();
        shopTxt = new javax.swing.JLabel();
        calcPanel = new javax.swing.JPanel();
        calcLbl = new javax.swing.JLabel();
        calcTxt = new javax.swing.JLabel();
        gamePanel = new javax.swing.JPanel();
        gameLbl = new javax.swing.JLabel();
        gameTxt = new javax.swing.JLabel();
        sidebarSeperator = new javax.swing.JSeparator();
        logoLbl = new javax.swing.JLabel();
        bannerPanel = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        homePage = new javax.swing.JPanel();
        homeLogoLbl = new javax.swing.JLabel();
        homeImgSep = new javax.swing.JSeparator();
        homeImg = new javax.swing.JLabel();
        shopPage = new javax.swing.JPanel();
        cartBtn = new javax.swing.JLabel();
        shopTitle = new javax.swing.JLabel();
        product2 = new javax.swing.JLabel();
        product1 = new javax.swing.JLabel();
        product4 = new javax.swing.JLabel();
        product3 = new javax.swing.JLabel();
        product6 = new javax.swing.JLabel();
        product5 = new javax.swing.JLabel();
        product8 = new javax.swing.JLabel();
        product7 = new javax.swing.JLabel();
        product8Desc = new javax.swing.JLabel();
        product1Desc = new javax.swing.JLabel();
        product2Desc = new javax.swing.JLabel();
        product3Desc = new javax.swing.JLabel();
        product4Desc = new javax.swing.JLabel();
        product5Desc = new javax.swing.JLabel();
        product6Desc = new javax.swing.JLabel();
        product7Desc = new javax.swing.JLabel();
        product8Btn = new javax.swing.JButton();
        product1Btn = new javax.swing.JButton();
        product2Btn = new javax.swing.JButton();
        product3Btn = new javax.swing.JButton();
        product4Btn = new javax.swing.JButton();
        product5Btn = new javax.swing.JButton();
        product6Btn = new javax.swing.JButton();
        product7Btn = new javax.swing.JButton();
        donateBtn = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        calcPage = new javax.swing.JPanel();
        dryerLabel = new javax.swing.JLabel();
        dryerTextField = new javax.swing.JTextField();
        tvLabel = new javax.swing.JLabel();
        tvTextField = new javax.swing.JTextField();
        kettleLabel = new javax.swing.JLabel();
        kettleTextField = new javax.swing.JTextField();
        waterHLabel = new javax.swing.JLabel();
        dryerTextField2 = new javax.swing.JTextField();
        appLabel = new javax.swing.JLabel();
        dryerTextField5 = new javax.swing.JTextField();
        washingMLabel = new javax.swing.JLabel();
        dryerTextField4 = new javax.swing.JTextField();
        freezerLabel = new javax.swing.JLabel();
        dryerTextField6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalEmissionsLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kmDrivenLabel = new javax.swing.JLabel();
        kmDrivenTextField = new javax.swing.JTextField();
        gasCompLabel = new javax.swing.JLabel();
        gasCompTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mCompLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        costPerHourLabel = new javax.swing.JLabel();
        costPerHourTextField = new javax.swing.JTextField();
        installationsLabel = new javax.swing.JLabel();
        installationTextField = new javax.swing.JTextField();
        mProLabel = new javax.swing.JLabel();
        mProTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        gamePage = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cartPage = new javax.swing.JPanel();
        detailsLbl = new javax.swing.JLabel();
        dNameLbl = new javax.swing.JLabel();
        dNameTxt = new javax.swing.JTextField();
        dPhoneLbl = new javax.swing.JLabel();
        dPhoneTxt = new javax.swing.JTextField();
        dAddressLbl = new javax.swing.JLabel();
        dAddressTxt = new javax.swing.JTextField();
        dCityLbl = new javax.swing.JLabel();
        dCityTxt = new javax.swing.JTextField();
        dCountyLbl = new javax.swing.JLabel();
        dCountyTxt = new javax.swing.JTextField();
        cardDetailsLbl = new javax.swing.JLabel();
        cNameLbl = new javax.swing.JLabel();
        cNameTxt = new javax.swing.JTextField();
        cCardnoLbl = new javax.swing.JLabel();
        cCardnoTxt = new javax.swing.JTextField();
        cExpiryLbl = new javax.swing.JLabel();
        cExpiryTxt = new javax.swing.JTextField();
        cCvvLbl = new javax.swing.JLabel();
        cCvvTxt = new javax.swing.JTextField();
        confirmBtn = new javax.swing.JButton();
        myCartLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1048, 552));

        sidebarMenu.setBackground(new java.awt.Color(141, 184, 124));

        homePanel.setBackground(new java.awt.Color(212, 232, 193));
        homePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePanelMouseClicked(evt);
            }
        });

        homeLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeBtn.png"))); // NOI18N

        homeTxt.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        homeTxt.setForeground(new java.awt.Color(30, 30, 30));
        homeTxt.setText("Home");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(homeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(homeTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        shopPanel.setBackground(new java.awt.Color(141, 184, 124));
        shopPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shopPanelMouseClicked(evt);
            }
        });

        shopLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopBtn.png"))); // NOI18N

        shopTxt.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        shopTxt.setForeground(new java.awt.Color(30, 30, 30));
        shopTxt.setText("Shop");

        javax.swing.GroupLayout shopPanelLayout = new javax.swing.GroupLayout(shopPanel);
        shopPanel.setLayout(shopPanelLayout);
        shopPanelLayout.setHorizontalGroup(
            shopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shopPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(shopLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(shopTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        shopPanelLayout.setVerticalGroup(
            shopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shopPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(shopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(shopTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shopLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        calcPanel.setBackground(new java.awt.Color(141, 184, 124));
        calcPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcPanelMouseClicked(evt);
            }
        });

        calcLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calculatorBtn.png"))); // NOI18N

        calcTxt.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        calcTxt.setForeground(new java.awt.Color(30, 30, 30));
        calcTxt.setText("Calculator");

        javax.swing.GroupLayout calcPanelLayout = new javax.swing.GroupLayout(calcPanel);
        calcPanel.setLayout(calcPanelLayout);
        calcPanelLayout.setHorizontalGroup(
            calcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(calcLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calcTxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        calcPanelLayout.setVerticalGroup(
            calcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(calcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calcTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calcLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        gamePanel.setBackground(new java.awt.Color(141, 184, 124));
        gamePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gamePanelMouseClicked(evt);
            }
        });

        gameLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gamesBtn.png"))); // NOI18N

        gameTxt.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        gameTxt.setForeground(new java.awt.Color(30, 30, 30));
        gameTxt.setText("Games");

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(gameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        sidebarSeperator.setForeground(new java.awt.Color(30, 30, 30));
        sidebarSeperator.setMinimumSize(new java.awt.Dimension(50, 15));
        sidebarSeperator.setPreferredSize(new java.awt.Dimension(50, 15));

        logoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        javax.swing.GroupLayout sidebarMenuLayout = new javax.swing.GroupLayout(sidebarMenu);
        sidebarMenu.setLayout(sidebarMenuLayout);
        sidebarMenuLayout.setHorizontalGroup(
            sidebarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(shopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(calcPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(gamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidebarMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidebarSeperator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(logoLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
        );
        sidebarMenuLayout.setVerticalGroup(
            sidebarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarMenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(logoLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sidebarSeperator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(shopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calcPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bannerPanel.setBackground(new java.awt.Color(212, 232, 193));

        exitBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(50, 50, 50));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exitBtn.png"))); // NOI18N
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoIcon.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout bannerPanelLayout = new javax.swing.GroupLayout(bannerPanel);
        bannerPanel.setLayout(bannerPanelLayout);
        bannerPanelLayout.setHorizontalGroup(
            bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerPanelLayout.createSequentialGroup()
                .addContainerGap(729, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitBtn)
                .addContainerGap())
        );
        bannerPanelLayout.setVerticalGroup(
            bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(exitBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMinimumSize(new java.awt.Dimension(849, 468));
        mainPanel.setLayout(new java.awt.CardLayout());

        homePage.setBackground(new java.awt.Color(255, 255, 255));
        homePage.setMinimumSize(new java.awt.Dimension(849, 468));

        homeLogoLbl.setBackground(new java.awt.Color(212, 232, 193));
        homeLogoLbl.setForeground(new java.awt.Color(212, 232, 193));
        homeLogoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        homeLogoLbl.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.lightGray));

        homeImgSep.setOrientation(javax.swing.SwingConstants.VERTICAL);

        homeImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homePageSide.jpg"))); // NOI18N

        javax.swing.GroupLayout homePageLayout = new javax.swing.GroupLayout(homePage);
        homePage.setLayout(homePageLayout);
        homePageLayout.setHorizontalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(homeLogoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(homeImgSep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeImg, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        homePageLayout.setVerticalGroup(
            homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePageLayout.createSequentialGroup()
                .addGroup(homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeImgSep)
                    .addGroup(homePageLayout.createSequentialGroup()
                        .addGroup(homePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(homePageLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(homeLogoLbl))
                            .addComponent(homeImg, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        mainPanel.add(homePage, "1");

        shopPage.setBackground(new java.awt.Color(255, 255, 255));
        shopPage.setMinimumSize(new java.awt.Dimension(849, 468));
        shopPage.setPreferredSize(new java.awt.Dimension(849, 468));
        shopPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Shopping Cart.png"))); // NOI18N
        cartBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartBtnMouseClicked(evt);
            }
        });
        shopPage.add(cartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, -1, -1));

        shopTitle.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        shopTitle.setForeground(new java.awt.Color(50, 50, 50));
        shopTitle.setText("Shop");
        shopPage.add(shopTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 20));

        product2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/productFiller.png"))); // NOI18N
        shopPage.add(product2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, -1));

        product1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/productFiller.png"))); // NOI18N
        shopPage.add(product1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        product4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/productFiller.png"))); // NOI18N
        shopPage.add(product4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, -1, -1));

        product3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/productFiller.png"))); // NOI18N
        shopPage.add(product3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, -1, -1));

        product6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/productFiller.png"))); // NOI18N
        shopPage.add(product6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        product5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/productFiller.png"))); // NOI18N
        shopPage.add(product5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        product8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/productFiller.png"))); // NOI18N
        shopPage.add(product8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));

        product7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/productFiller.png"))); // NOI18N
        shopPage.add(product7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        product8Desc.setForeground(new java.awt.Color(50, 50, 50));
        product8Desc.setText("Name + Price");
        shopPage.add(product8Desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 80, 30));

        product1Desc.setForeground(new java.awt.Color(50, 50, 50));
        product1Desc.setText("Name + Price");
        shopPage.add(product1Desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 80, 30));

        product2Desc.setForeground(new java.awt.Color(50, 50, 50));
        product2Desc.setText("Name + Price");
        shopPage.add(product2Desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 80, 30));

        product3Desc.setForeground(new java.awt.Color(50, 50, 50));
        product3Desc.setText("Name + Price");
        shopPage.add(product3Desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 80, 30));

        product4Desc.setForeground(new java.awt.Color(50, 50, 50));
        product4Desc.setText("Name + Price");
        shopPage.add(product4Desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 80, 30));

        product5Desc.setForeground(new java.awt.Color(50, 50, 50));
        product5Desc.setText("Name + Price");
        shopPage.add(product5Desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 80, 30));

        product6Desc.setForeground(new java.awt.Color(50, 50, 50));
        product6Desc.setText("Name + Price");
        shopPage.add(product6Desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 80, 30));

        product7Desc.setForeground(new java.awt.Color(50, 50, 50));
        product7Desc.setText("Name + Price");
        shopPage.add(product7Desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 80, 30));

        product8Btn.setText("Add to Cart");
        shopPage.add(product8Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, -1, -1));

        product1Btn.setText("Add to Cart");
        shopPage.add(product1Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        product2Btn.setText("Add to Cart");
        shopPage.add(product2Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        product3Btn.setText("Add to Cart");
        shopPage.add(product3Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        product4Btn.setText("Add to Cart");
        shopPage.add(product4Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        product5Btn.setText("Add to Cart");
        shopPage.add(product5Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        product6Btn.setText("Add to Cart");
        shopPage.add(product6Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, -1, -1));

        product7Btn.setText("Add to Cart");
        shopPage.add(product7Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        donateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Donate.png"))); // NOI18N
        shopPage.add(donateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 60, 50));

        jSeparator2.setForeground(new java.awt.Color(50, 50, 50));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        shopPage.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 0, -1, 470));

        mainPanel.add(shopPage, "2");

        calcPage.setBackground(new java.awt.Color(255, 255, 255));
        calcPage.setMinimumSize(new java.awt.Dimension(849, 468));

        dryerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dryerLabel.setText("Dryer");

        dryerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dryerTextFieldActionPerformed(evt);
            }
        });

        tvLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tvLabel.setText("Tv");

        tvTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvTextFieldActionPerformed(evt);
            }
        });

        kettleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kettleLabel.setText("Kettle");

        kettleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kettleTextFieldActionPerformed(evt);
            }
        });

        waterHLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waterHLabel.setText("Water Heater");

        dryerTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dryerTextField2ActionPerformed(evt);
            }
        });

        appLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appLabel.setText("Appliances");

        dryerTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dryerTextField5ActionPerformed(evt);
            }
        });

        washingMLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        washingMLabel.setText("Washing Machine");

        dryerTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dryerTextField4ActionPerformed(evt);
            }
        });

        freezerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        freezerLabel.setText("Freezer");

        dryerTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dryerTextField6ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("per year");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("You use");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("kwh Per month!");

        totalEmissionsLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("per month");

        kmDrivenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kmDrivenLabel.setText("Kilometres Driven");

        kmDrivenTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kmDrivenTextFieldActionPerformed(evt);
            }
        });

        gasCompLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gasCompLabel.setText("Gas Comsumption");

        gasCompTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gasCompTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("How much gas does your car emit?");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Your car emits ");

        mCompLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("How much energy do you use?");

        costPerHourLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        costPerHourLabel.setText("Cost of renewable electricity per hour");

        costPerHourTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costPerHourTextFieldActionPerformed(evt);
            }
        });

        installationsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        installationsLabel.setText("Installation Costs");

        installationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                installationTextFieldActionPerformed(evt);
            }
        });

        mProLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mProLabel.setText("Montlhy Proudction");

        mProTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mProTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("How much energy will you save on when you switch?");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("You will save");

        javax.swing.GroupLayout calcPageLayout = new javax.swing.GroupLayout(calcPage);
        calcPage.setLayout(calcPageLayout);
        calcPageLayout.setHorizontalGroup(
            calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcPageLayout.createSequentialGroup()
                .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calcPageLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(calcPageLayout.createSequentialGroup()
                                .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kmDrivenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(calcPageLayout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(kmDrivenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gasCompLabel)
                                    .addGroup(calcPageLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(gasCompTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel9)
                                        .addGap(9, 9, 9)
                                        .addComponent(totalEmissionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7))))
                            .addGroup(calcPageLayout.createSequentialGroup()
                                .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dryerTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                    .addComponent(dryerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(calcPageLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tvLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                            .addComponent(tvTextField))
                                        .addGap(2, 2, 2)
                                        .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(kettleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(kettleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(waterHLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(calcPageLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(dryerTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(dryerTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(appLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(washingMLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(calcPageLayout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(dryerTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(dryerTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(freezerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(calcPageLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(mCompLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calcPageLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(312, 312, 312))
                            .addGroup(calcPageLayout.createSequentialGroup()
                                .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(costPerHourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(calcPageLayout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(costPerHourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(installationsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(calcPageLayout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(installationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mProLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(calcPageLayout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(mProTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(calcPageLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel10)))
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(calcPageLayout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jLabel11)
                    .addContainerGap(372, Short.MAX_VALUE)))
            .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(calcPageLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jLabel12)
                    .addContainerGap(695, Short.MAX_VALUE)))
        );
        calcPageLayout.setVerticalGroup(
            calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calcPageLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(calcPageLayout.createSequentialGroup()
                            .addComponent(freezerLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dryerTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(calcPageLayout.createSequentialGroup()
                            .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(appLabel)
                                .addComponent(washingMLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dryerTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dryerTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(calcPageLayout.createSequentialGroup()
                            .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(kettleLabel)
                                .addComponent(waterHLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(kettleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dryerTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(tvTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(calcPageLayout.createSequentialGroup()
                            .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dryerLabel)
                                .addComponent(tvLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dryerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                    .addGroup(calcPageLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(mCompLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalEmissionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(calcPageLayout.createSequentialGroup()
                        .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kmDrivenLabel)
                            .addComponent(gasCompLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kmDrivenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gasCompTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59)
                .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calcPageLayout.createSequentialGroup()
                        .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(installationsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costPerHourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(installationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costPerHourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(calcPageLayout.createSequentialGroup()
                        .addComponent(mProLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mProTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calcPageLayout.createSequentialGroup()
                    .addContainerGap(296, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(158, 158, 158)))
            .addGroup(calcPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, calcPageLayout.createSequentialGroup()
                    .addContainerGap(399, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(55, 55, 55)))
        );

        mainPanel.add(calcPage, "3");

        gamePage.setBackground(new java.awt.Color(255, 255, 255));
        gamePage.setMinimumSize(new java.awt.Dimension(849, 468));

        jLabel5.setForeground(new java.awt.Color(50, 50, 50));
        jLabel5.setText("Game");

        javax.swing.GroupLayout gamePageLayout = new javax.swing.GroupLayout(gamePage);
        gamePage.setLayout(gamePageLayout);
        gamePageLayout.setHorizontalGroup(
            gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePageLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(761, Short.MAX_VALUE))
        );
        gamePageLayout.setVerticalGroup(
            gamePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePageLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(427, Short.MAX_VALUE))
        );

        mainPanel.add(gamePage, "4");

        cartPage.setBackground(new java.awt.Color(255, 255, 255));
        cartPage.setForeground(new java.awt.Color(50, 50, 50));
        cartPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartPageMouseClicked(evt);
            }
        });

        detailsLbl.setBackground(new java.awt.Color(255, 255, 255));
        detailsLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        detailsLbl.setForeground(new java.awt.Color(50, 50, 50));
        detailsLbl.setText("Enter your Details:");

        dNameLbl.setBackground(new java.awt.Color(255, 255, 255));
        dNameLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dNameLbl.setForeground(new java.awt.Color(50, 50, 50));
        dNameLbl.setText("Name: ");

        dNameTxt.setBackground(new java.awt.Color(255, 255, 255));
        dNameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dNameTxtActionPerformed(evt);
            }
        });

        dPhoneLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dPhoneLbl.setForeground(new java.awt.Color(50, 50, 50));
        dPhoneLbl.setText("Phone No. :");

        dPhoneTxt.setBackground(new java.awt.Color(255, 255, 255));
        dPhoneTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        dAddressLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dAddressLbl.setForeground(new java.awt.Color(50, 50, 50));
        dAddressLbl.setText("Address:");

        dAddressTxt.setBackground(new java.awt.Color(255, 255, 255));
        dAddressTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        dCityLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dCityLbl.setForeground(new java.awt.Color(50, 50, 50));
        dCityLbl.setText("City/Town:");

        dCityTxt.setBackground(new java.awt.Color(255, 255, 255));
        dCityTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dCityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dCityTxtActionPerformed(evt);
            }
        });

        dCountyLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dCountyLbl.setForeground(new java.awt.Color(50, 50, 50));
        dCountyLbl.setText("County:");

        dCountyTxt.setBackground(new java.awt.Color(255, 255, 255));
        dCountyTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dCountyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dCountyTxtActionPerformed(evt);
            }
        });

        cardDetailsLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cardDetailsLbl.setForeground(new java.awt.Color(50, 50, 50));
        cardDetailsLbl.setText("Card Details:");

        cNameLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cNameLbl.setForeground(new java.awt.Color(50, 50, 50));
        cNameLbl.setText("Name:");

        cNameTxt.setBackground(new java.awt.Color(255, 255, 255));
        cNameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNameTxtActionPerformed(evt);
            }
        });

        cCardnoLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cCardnoLbl.setForeground(new java.awt.Color(50, 50, 50));
        cCardnoLbl.setText("Card No. :");

        cCardnoTxt.setBackground(new java.awt.Color(255, 255, 255));
        cCardnoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cCardnoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCardnoTxtActionPerformed(evt);
            }
        });

        cExpiryLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cExpiryLbl.setForeground(new java.awt.Color(50, 50, 50));
        cExpiryLbl.setText("Expiry:");

        cExpiryTxt.setBackground(new java.awt.Color(255, 255, 255));
        cExpiryTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cExpiryTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cExpiryTxtActionPerformed(evt);
            }
        });

        cCvvLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cCvvLbl.setForeground(new java.awt.Color(50, 50, 50));
        cCvvLbl.setText("CVV:");

        cCvvTxt.setBackground(new java.awt.Color(255, 255, 255));
        cCvvTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cCvvTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCvvTxtActionPerformed(evt);
            }
        });

        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBtnActionPerformed(evt);
            }
        });

        myCartLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        myCartLbl.setForeground(new java.awt.Color(50, 50, 50));
        myCartLbl.setText("My Cart");

        jSeparator1.setForeground(new java.awt.Color(50, 50, 50));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout cartPageLayout = new javax.swing.GroupLayout(cartPage);
        cartPage.setLayout(cartPageLayout);
        cartPageLayout.setHorizontalGroup(
            cartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartPageLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(myCartLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(cartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cartPageLayout.createSequentialGroup()
                        .addGroup(cartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cCardnoLbl)
                            .addComponent(cNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cExpiryLbl)
                            .addComponent(cCvvLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cExpiryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cCvvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cardDetailsLbl)
                    .addGroup(cartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dAddressLbl)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartPageLayout.createSequentialGroup()
                            .addComponent(detailsLbl)
                            .addGap(76, 76, 76))
                        .addComponent(dNameLbl)
                        .addComponent(dNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                        .addComponent(dPhoneLbl)
                        .addComponent(dPhoneTxt))
                    .addComponent(dAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dCityLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dCountyLbl)
                    .addComponent(dCountyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(cartPageLayout.createSequentialGroup()
                        .addComponent(cCardnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(confirmBtn)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        cartPageLayout.setVerticalGroup(
            cartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartPageLayout.createSequentialGroup()
                .addGroup(cartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cartPageLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(myCartLbl))
                    .addGroup(cartPageLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(detailsLbl)))
                .addGap(10, 10, 10)
                .addComponent(dNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dPhoneLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dAddressLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dCityLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(dCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dCountyLbl)
                .addGap(4, 4, 4)
                .addComponent(dCountyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardDetailsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cNameLbl)
                    .addComponent(cExpiryLbl)
                    .addComponent(cExpiryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cartPageLayout.createSequentialGroup()
                        .addGroup(cartPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cCardnoLbl)
                            .addComponent(cCvvLbl)
                            .addComponent(cCvvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cCardnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartPageLayout.createSequentialGroup()
                        .addComponent(confirmBtn)
                        .addGap(19, 19, 19))))
            .addComponent(jSeparator1)
        );

        dPhoneLbl.getAccessibleContext().setAccessibleName("phoneLbl");

        mainPanel.add(cartPage, "5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bannerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bannerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void homePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelMouseClicked
        setColor(homePanel);
        resetColor(shopPanel);
        resetColor(gamePanel);
        resetColor(calcPanel);
        
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "1");
    }//GEN-LAST:event_homePanelMouseClicked

    private void shopPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shopPanelMouseClicked
        setColor(shopPanel);
        resetColor(homePanel);
        resetColor(gamePanel);
        resetColor(calcPanel);
        
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "2");
    }//GEN-LAST:event_shopPanelMouseClicked

    private void calcPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcPanelMouseClicked
        setColor(calcPanel);
        resetColor(shopPanel);
        resetColor(gamePanel);
        resetColor(homePanel);
        
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "3");
    }//GEN-LAST:event_calcPanelMouseClicked

    private void gamePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gamePanelMouseClicked
        setColor(gamePanel);
        resetColor(shopPanel);
        resetColor(homePanel);
        resetColor(calcPanel);
        
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "4");
    }//GEN-LAST:event_gamePanelMouseClicked

    private void dryerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dryerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dryerTextFieldActionPerformed

    private void tvTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvTextFieldActionPerformed

    private void dryerTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dryerTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dryerTextField2ActionPerformed

    private void kettleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kettleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kettleTextFieldActionPerformed

    private void dryerTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dryerTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dryerTextField4ActionPerformed

    private void dryerTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dryerTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dryerTextField5ActionPerformed

    private void dryerTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dryerTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dryerTextField6ActionPerformed

    private void kmDrivenTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kmDrivenTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kmDrivenTextFieldActionPerformed

    private void gasCompTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gasCompTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gasCompTextFieldActionPerformed

    private void costPerHourTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costPerHourTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costPerHourTextFieldActionPerformed

    private void installationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_installationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_installationTextFieldActionPerformed

    private void mProTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mProTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mProTextFieldActionPerformed

    private void cartPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartPageMouseClicked
        setColor(shopPanel);
        resetColor(homePanel);
        resetColor(gamePanel);
        resetColor(calcPanel);
        
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "5");
    }//GEN-LAST:event_cartPageMouseClicked

    private void cartBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartBtnMouseClicked
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "5");
    }//GEN-LAST:event_cartBtnMouseClicked

    private void dCityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dCityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dCityTxtActionPerformed

    private void dCountyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dCountyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dCountyTxtActionPerformed

    private void dNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dNameTxtActionPerformed

    private void cNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cNameTxtActionPerformed

    private void cCardnoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCardnoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCardnoTxtActionPerformed

    private void cExpiryTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cExpiryTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cExpiryTxtActionPerformed

    private void cCvvTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCvvTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCvvTxtActionPerformed

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // TODO add your handling code here:
        customer c = new customer();
            c.setName(dNameTxt.getText());
            c.setPhoneNo(dPhoneTxt.getText());
            c.setAddress(dAddressTxt.getText());
            c.setCity(dCityTxt.getText());
            c.setCounty(dCountyTxt.getText());
            
            c.setCardName(cNameTxt.getText());
            c.setCardNo(cCardnoTxt.getText());
            c.setExpiry(cExpiryTxt.getText());
            c.setCvv(cCvvTxt.getText());
            customers.add(c);
    }//GEN-LAST:event_confirmBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EcowiseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EcowiseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EcowiseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EcowiseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EcowiseGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appLabel;
    private javax.swing.JPanel bannerPanel;
    private javax.swing.JLabel cCardnoLbl;
    private javax.swing.JTextField cCardnoTxt;
    private javax.swing.JLabel cCvvLbl;
    private javax.swing.JTextField cCvvTxt;
    private javax.swing.JLabel cExpiryLbl;
    private javax.swing.JTextField cExpiryTxt;
    private javax.swing.JLabel cNameLbl;
    private javax.swing.JTextField cNameTxt;
    private javax.swing.JLabel calcLbl;
    private javax.swing.JPanel calcPage;
    private javax.swing.JPanel calcPanel;
    private javax.swing.JLabel calcTxt;
    private javax.swing.JLabel cardDetailsLbl;
    private javax.swing.JLabel cartBtn;
    private javax.swing.JPanel cartPage;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel costPerHourLabel;
    private javax.swing.JTextField costPerHourTextField;
    private javax.swing.JLabel dAddressLbl;
    private javax.swing.JTextField dAddressTxt;
    private javax.swing.JLabel dCityLbl;
    private javax.swing.JTextField dCityTxt;
    private javax.swing.JLabel dCountyLbl;
    private javax.swing.JTextField dCountyTxt;
    private javax.swing.JLabel dNameLbl;
    private javax.swing.JTextField dNameTxt;
    private javax.swing.JLabel dPhoneLbl;
    private javax.swing.JTextField dPhoneTxt;
    private javax.swing.JLabel detailsLbl;
    private javax.swing.JLabel donateBtn;
    private javax.swing.JLabel dryerLabel;
    private javax.swing.JTextField dryerTextField;
    private javax.swing.JTextField dryerTextField2;
    private javax.swing.JTextField dryerTextField4;
    private javax.swing.JTextField dryerTextField5;
    private javax.swing.JTextField dryerTextField6;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel freezerLabel;
    private javax.swing.JLabel gameLbl;
    private javax.swing.JPanel gamePage;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JLabel gameTxt;
    private javax.swing.JLabel gasCompLabel;
    private javax.swing.JTextField gasCompTextField;
    private javax.swing.JLabel homeImg;
    private javax.swing.JSeparator homeImgSep;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JLabel homeLogoLbl;
    private javax.swing.JPanel homePage;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel homeTxt;
    private javax.swing.JTextField installationTextField;
    private javax.swing.JLabel installationsLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel kettleLabel;
    private javax.swing.JTextField kettleTextField;
    private javax.swing.JLabel kmDrivenLabel;
    private javax.swing.JTextField kmDrivenTextField;
    private javax.swing.JLabel logoLbl;
    private javax.swing.JLabel mCompLabel1;
    private javax.swing.JLabel mProLabel;
    private javax.swing.JTextField mProTextField;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel myCartLbl;
    private javax.swing.JLabel product1;
    private javax.swing.JButton product1Btn;
    private javax.swing.JLabel product1Desc;
    private javax.swing.JLabel product2;
    private javax.swing.JButton product2Btn;
    private javax.swing.JLabel product2Desc;
    private javax.swing.JLabel product3;
    private javax.swing.JButton product3Btn;
    private javax.swing.JLabel product3Desc;
    private javax.swing.JLabel product4;
    private javax.swing.JButton product4Btn;
    private javax.swing.JLabel product4Desc;
    private javax.swing.JLabel product5;
    private javax.swing.JButton product5Btn;
    private javax.swing.JLabel product5Desc;
    private javax.swing.JLabel product6;
    private javax.swing.JButton product6Btn;
    private javax.swing.JLabel product6Desc;
    private javax.swing.JLabel product7;
    private javax.swing.JButton product7Btn;
    private javax.swing.JLabel product7Desc;
    private javax.swing.JLabel product8;
    private javax.swing.JButton product8Btn;
    private javax.swing.JLabel product8Desc;
    private javax.swing.JLabel shopLbl;
    private javax.swing.JPanel shopPage;
    private javax.swing.JPanel shopPanel;
    private javax.swing.JLabel shopTitle;
    private javax.swing.JLabel shopTxt;
    private javax.swing.JPanel sidebarMenu;
    private javax.swing.JSeparator sidebarSeperator;
    private javax.swing.JLabel totalEmissionsLabel;
    private javax.swing.JLabel tvLabel;
    private javax.swing.JTextField tvTextField;
    private javax.swing.JLabel washingMLabel;
    private javax.swing.JLabel waterHLabel;
    // End of variables declaration//GEN-END:variables
}
